import { Task } from "@/entities/Task";
import { COLORS } from "./Colors";

export const TASKS: Task[] = [
	{
		id: 1,
		title: "API Integration Setup",
		category: "Frontend Development",
		time_estimate: "6h estimated",
		status: "todo",
		media_icon: "play",
		icon_name: "code",
		right_text: "High Priority",
		time_logged: "2h 15m",
		dot_color: COLORS.primary,
		progress_percent: "19%",
		time_stamp: "00:00:00",
		time_elapsed: 0,
	},
	{
		id: 2,
		title: "Database Migration",
		category: "Backend",
		time_estimate: "4h estimated",
		status: "todo",
		media_icon: "play",
		icon_name: "database",
		right_text: "High Priority",
		time_logged: "3h 30m",
		dot_color: COLORS.primary,
		progress_percent: "45%",
		time_stamp: "00:00:00",
		time_elapsed: 0,
	},
	{
		id: 3,
		title: "Mobile UI Testing",
		category: "QA",
		time_estimate: "2h estimated",
		status: "todo",
		media_icon: "play",
		icon_name: "mobile-screen-button",
		right_text: "High Priority",
		time_logged: "1h 30m",
		dot_color: COLORS.primary,
		progress_percent: "19%",
		time_stamp: "00:00:00",
		time_elapsed: 0,
	},
	{
		id: 4,
		title: "Analytics Dashboard",
		category: "Frontend",
		time_estimate: "6h estimated",
		status: "todo",
		media_icon: "play",
		icon_name: "chart-line",
		right_text: "Medium Priority",
		time_logged: "2h 15m",
		dot_color: COLORS.primary,
		progress_percent: "19%",
		time_stamp: "00:00:00",
		time_elapsed: 0,
	},
	{
		id: 5,
		title: "User Authentication",
		category: "Backend",
		time_estimate: "4h estimated",
		status: "completed",
		media_icon: "check",
		icon_name: "users",
		right_text: "3.5h logged",
		time_logged: "3h 30m",
		dot_color: COLORS.primary,
		progress_percent: "19%",
		time_stamp: "00:00:00",
		time_elapsed: 0,
	},
];
