export const TASKS = [
	{
		id: 1,
		title: "API Integration Setup",
		category: "Frontend Development",
		time_estimate: "6h estimated",
		status: "tracking",
		media_icon: "pause",
		icon_name: "code",
		right_text: "02:34:15",
	},
	{
		id: 2,
		title: "Database Migration",
		category: "Backend",
		time_estimate: "4h estimated",
		status: "todo",
		media_icon: "play",
		icon_name: "database",
		right_text: "High Priority",
	},
	{
		id: 3,
		title: "Mobile UI Testing",
		category: "QA",
		time_estimate: "2h estimated",
		status: "todo",
		media_icon: "play",
		icon_name: "mobile-screen-button",
		right_text: "High Priority",
	},
	{
		id: 4,
		title: "Analytics Dashboard",
		category: "Frontend",
		time_estimate: "6h estimated",
		status: "todo",
		media_icon: "play",
		icon_name: "chart-line",
		right_text: "Medium Priority",
	},
	{
		id: 5,
		title: "User Authentication",
		category: "Backend",
		time_estimate: "4h estimated",
		status: "completed",
		media_icon: "check",
		icon_name: "users",

		right_text: "3.5h logged",
	},
];
